title: Typography Space
description: A website with a blog
header_text: My Dream Blog
footer_text: Copyright 2020 Your name
header_feature_image: ../uploads/joel-fulgencio-ktwcwml75iy-unsplash.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
