title: Typography Space
description: ""
header_text: ""
footer_text: Copyright 2020 Daniela Hernandez
header_feature_image: ../uploads/joel-fulgencio-ktwcwml75iy-unsplash.jpg
bannerheight: 20vmax
logo: ../uploads/negro-con-círculo-blanco-despacho-jurídico-logo.png
favicon: ../uploads/negro-con-círculo-blanco-despacho-jurídico-logo.png
gridlayout: false
fixednavbar: false
upzoom: true
