title: Typography Space
description: ""
header_text: Some Fun Facts About Typography
footer_text: Copyright 2020 Daniela Hernandez
header_feature_image: ../uploads/joel-fulgencio-ktwcwml75iy-unsplash.jpg
bannerheight: 20vmax
logo: ../uploads/negro-azul-rosa-neón-club-logotipo.png
favicon: ../uploads/negro-azul-rosa-neón-club-logotipo.png
gridlayout: false
fixednavbar: false
upzoom: true
