title: Typography Space
description: ""
header_text: Typography Space
footer_text: Copyright 2020 Daniela Hernandez
header_feature_image: ../uploads/joel-fulgencio-ktwcwml75iy-unsplash.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
